server:
  port: 19094

spring:
  # spring application configuration
  application:
    name: routing-service-provider

  # register center configuration
  cloud:
    nacos:
      discovery:
        server-addr: sca-label-routing-nacos-server:8848
        username: 'nacos'
        password: 'nacos'
        metadata:
          version: v2
          region: dev
          zone: zone2

management:
  server:
    port: 30094
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
