server:
  port: 19098

spring:
  application:
    name: gateway-consumer-example

  cloud:
    nacos:
      discovery:
        server-addr: sca-label-routing-nacos-server:8848
        username: 'nacos'
        password: 'nacos'

    # Regional affinity routing configuration
    governance:
      routing:
        region: dev
        zone: zone1
        # rule: RandomRule

    # Gateway route config
    gateway:
      routes:
        - id: label-routing-test-route
          uri: lb://routing-service-provider
          predicates:
            - Path=/routing-service-provider/**
          filters:
            - StripPrefix=1

management:
  server:
    port: 30098
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
