server:
  port: 19095

spring:
  application:
    name: openfeign-service-consumer

  cloud:

    # register center configuration
    nacos:
      discovery:
        fail-fast: true
        server-addr: 127.0.0.1:8848
        username: 'nacos'
        password: 'nacos'

    # label routing configuration
    governance:
      routing:
        region: dev
        zone: zone1
      # rule: RandomRule

management:
  server:
    port: 30001
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
